/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.awt.Toolkit;
import javax.swing.*;
import java.io.*;
/**
 *
 * @author asus
 */
public class FormNotepad extends javax.swing.JFrame {
 private File currentFile;
    /**
     * Creates new form FormNotepad
     */
    public FormNotepad() {
        initComponents();
        setIconImage(
        Toolkit.getDefaultToolkit().getImage(
         getClass().getResource("/Icon/icon.png")
        )
    );
        setTitle("Notepad");
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        pack();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newitem = new javax.swing.JMenuItem();
        openitem = new javax.swing.JMenuItem();
        saveitem = new javax.swing.JMenuItem();
        saveasitem = new javax.swing.JMenuItem();
        editmenu = new javax.swing.JMenu();
        exitmenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        textarea.setColumns(20);
        textarea.setRows(5);
        jScrollPane2.setViewportView(textarea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        newitem.setText("New");
        newitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newitemActionPerformed(evt);
            }
        });
        jMenu1.add(newitem);

        openitem.setText("Open");
        openitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openitemActionPerformed(evt);
            }
        });
        jMenu1.add(openitem);

        saveitem.setText("Save");
        saveitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveitemActionPerformed(evt);
            }
        });
        jMenu1.add(saveitem);

        saveasitem.setText("Save as");
        saveasitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveasitemActionPerformed(evt);
            }
        });
        jMenu1.add(saveasitem);

        jMenuBar1.add(jMenu1);

        editmenu.setText("Edit");
        jMenuBar1.add(editmenu);

        exitmenu.setText("Exit");
        exitmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitmenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(exitmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newitemActionPerformed
    textarea.setText("");
    currentFile = null;
    setTitle("Notepad - New File");
    }//GEN-LAST:event_newitemActionPerformed

    private void saveasitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveasitemActionPerformed
   JFileChooser chooser = new JFileChooser();
    int option = chooser.showSaveDialog(this);

    if (option == JFileChooser.APPROVE_OPTION) {
        currentFile = chooser.getSelectedFile();
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(currentFile))) {
            textarea.write(bw);
            setTitle("Notepad - " + currentFile.getName());
            JOptionPane.showMessageDialog(this, "File berhasil disimpan");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan file");
        }
    }
    }//GEN-LAST:event_saveasitemActionPerformed

    private void openitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openitemActionPerformed
 JFileChooser chooser = new JFileChooser();
    int option = chooser.showOpenDialog(this);

    if (option == JFileChooser.APPROVE_OPTION) {
        currentFile = chooser.getSelectedFile();
        try (BufferedReader br = new BufferedReader(new FileReader(currentFile))) {
            textarea.read(br, null);
            setTitle("Notepad - " + currentFile.getName());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Gagal membuka file");
        }
    }
    }//GEN-LAST:event_openitemActionPerformed

    private void saveitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveitemActionPerformed
     if (currentFile == null) {
        saveasitemActionPerformed(evt);
        return;
    }

    try (BufferedWriter bw = new BufferedWriter(new FileWriter(currentFile))) {
        textarea.write(bw);
        JOptionPane.showMessageDialog(this, "File berhasil disimpan");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan file");
    }
    }//GEN-LAST:event_saveitemActionPerformed

    private void exitmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitmenuActionPerformed
     int confirm = JOptionPane.showConfirmDialog(
        this,
        "Keluar dari aplikasi?",
        "Konfirmasi",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_exitmenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNotepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNotepad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editmenu;
    private javax.swing.JMenu exitmenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem newitem;
    private javax.swing.JMenuItem openitem;
    private javax.swing.JMenuItem saveasitem;
    private javax.swing.JMenuItem saveitem;
    private javax.swing.JTextArea textarea;
    // End of variables declaration//GEN-END:variables
}
